name: Integration

on: [workflow_dispatch, push]

jobs:
  ci:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          show-progress: false

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Lint & Format with Ruff
        run: |
          pip install ruff
          ruff --output-format=github .
          ruff format .
      
      - name: Check for uncommitted changes
        run: |
          if ! git diff --quiet; then
            echo "There are uncommitted changes after running ruff format. Please run 'ruff format' locally and try again."
            exit 1
          fi